config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "application#index"

  resources :cards do
    member do
      get 'done'
    end
  end

  resources :plans

  resources :routines do
    member do
      get 'done'
    end
  end

  resources :months
  resources :application, onry: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :month
  belongs_to :plan
  
  validates :title, presence: true
  validates :content, presence: true
end

app/models/month.rb
class Month < ApplicationRecord
  has_many :cards
  
  validates :name, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :cards, dependent: :destroy

  validates :content, presence: true
end

app/models/routine.rb
class Routine < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    if user_signed_in?
      redirect_to cards_path
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    cards = Card.includes(:month)
    @months = Month.all
    @plans = Plan.all
    @routines = Routine.all
  end

  def new
    @card = Card.new
    @plans = Plan.all
  end

  def create
    Card.create(card_params)
    redirect_to root_path
  end

  def show
    @card = Card.find(params[:id])
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    @card.update(card_params)
    redirect_to root_path
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to root_path
  end

  def done
    @card = Card.find(params[:id])
    if @card.status.blank?
      @card.update(status: "done")
    else
      @card.update(status: "")
    end
    redirect_to root_path
  end

  private
  def card_params
    params.require(:card).permit(:title, :content, :month_id, :plan_id)
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def show
    @month = Month.find(params[:id])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def new
    @plan = Plan.new
  end

  def create
    Plan.create(plan_params)
    redirect_to root_path
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plam.update(plan_params)
    redirect_to root_path
  end

  def dstroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to root_path
  end

  private
  def plan_params
    params.require(:plan).permit(:content)
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def new
    @routine = Routine.new
  end

  def create
    Routine.create(routine_params)
    redirect_to root_path
  end

  def show
    @routine = Routine.find(params[:id])
  end

  def edit
    @routine = Routine.find(params[:id])
  end

  def update
    @routine = Routine.find(params[:id])
    @routine.update(routine_params)
    redirect_to root_path
  end

  def destroy
    @routine = Routine.find(params[:id])
    @routine.destroy
    redirect_to root_path
  end

  def done
    @routine = Routine.find(params[:id])
    @routine.update(count: (@routine.count += 1))
    redirect_to root_path
  end

  private
  def routine_params
    params.require(:routine).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/application/index.html.haml
%h1 PDCA_APP
= link_to "Log_in", new_user_session_path
= link_to "Sign_up", new_user_registration_path

app/views/cards/edit.html.haml
= form_with model: @card, local: true do |f|
  = f.text_field :title, placeholder: :タイトル
  = f.text_area :content
  = f.collection_select :plan_id, Plan.group(:content).order(id: :desc), :id, :content, {prompt: ""}
  = f.collection_select :month_id, Month.group(:name).order(:id), :id, :name, {prompt: ""}
  = f.submit 'SEND'

app/views/cards/index.html.haml
.container
  .upper-container
    .plan-box
      %ul.plans
        - @plans.each do |plan|
          %li.plan
            = link_to "/plans/#{plan.id}" do
              = plan.content
            = plan.cards.length
            = plan.cards.where(status: "done").length
            - if plan.cards.length != 0
              = "達成率#{((plan.cards.where(status: "done").length).to_f / (plan.cards.length).to_f * 100).round(1)}%"

    .routines-box
      %ul.routines
        - @routines.each do |routine|
          %li.routine
            = link_to "/routines/#{routine.id}" do
              = routine.title
            = routine.count
            = link_to "done", "/routines/#{routine.id}/done"
        

  .lower-container
    %ul.month-lists
      - @months.each do |month|
        %li.month-list
          = link_to "/months/#{month.id}" do
            = month.name
          - month.cards.each do |card|
            = link_to "/cards/#{card.id}" do
              .card
                .card__title
                  = card.title
                .card__content
                  = card.content
                .card__plan
                  = card.plan.content
                  = link_to "done", "/cards/#{card.id}/done"
                  = link_to "削除", "/cards/#{card.id}", method: :delete

app/views/cards/new.html.haml
= form_with model: @card, local: true do |f|
  = f.text_field :title, placeholder: :タイトル
  = f.text_area :content
  = f.collection_select :plan_id, Plan.group(:content).order(id: :desc), :id, :content, {prompt: ""}
  = f.collection_select :month_id, Month.group(:name).order(:id), :id, :name, {prompt: ""}
  = f.submit

app/views/cards/show.html.haml
= @card.title
= @card.content
= @card.plan.content
= link_to "done", "/cards/#{@card.id}/done"
= link_to "編集", edit_card_path
= link_to "削除", "/cards/#{@card.id}", method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pdca
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      %header
        = link_to "TOP", root_path
        = link_to "NEW", new_card_path
        = link_to "NEW_PLAN", new_plan_path
        = link_to "NEW_ROUTINE", new_routine_path
        = link_to "Log_in", new_user_session_path
        = link_to "Sign_up", new_user_registration_path
      = yield

app/views/months/show.html.haml
= @month.name
%ul.cards
  - @month.cards.each do |card|
    %li.card
      .card__title
        = card.title
      .card__content
        = card.content
      .card__plan
        = card.plan.content
        = link_to "done", "/cards/#{card.id}/done"
        = link_to "削除", "/cards/#{card.id}", method: :delete

app/views/plans/edit.html.haml
= form_with model: @plan, local: true do |f|
  = f.text_field :content
  = f.submit 'SEND'

app/views/plans/new.html.haml
= form_with model: @plan, local: true do |f|
  = f.text_field :content
  = f.submit 'SEND'

app/views/plans/show.html.haml
= @plan.content
- @plan.cards.each do |card|
  = card.month.name
  = card.title
  - if card.status == "done"
    "完了"
  - else
    "未完了"
= link_to "編集", edit_plan_path
= link_to "削除", "/plans/#{@plan.id}", method: :delete

app/views/routines/edit.html.haml
= form_with model: @routine, local: true do |f|
  = f.text_field :title
  = f.text_area :content
  = f.submit

app/views/routines/new.html.haml
= form_with model: @routine, local: true do |f|
  = f.text_field :title
  = f.text_area :content
  = f.submit

app/views/routines/show.html.haml
= @routine.title
= @routine.content
= @routine.count
= link_to "編集", edit_routine_path
= link_to "削除", "/routines/#{@routine.id}", method: :delete

app/views/shared/_top.html.haml
%h1 PDCA_APP
= link_to "Log_in", new_user_session_path
= link_to "Sign_up", new_user_registration_path